OLED_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes           # Enable N-Key Rollover
VIA_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes        # Mouse keys
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
